In [3]:
my_list = [1,2,3]


In [6]:
import numpy as np


In [16]:
arr = np.array(my_list)

In [22]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [23]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.arange(0,13,2)


array([ 0,  2,  4,  6,  8, 10, 12])

In [32]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [35]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [36]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [37]:
np.eye(8)


array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [38]:
np.random.rand(5)

array([0.60888957, 0.15582032, 0.64314979, 0.28786633, 0.10518206])

In [41]:
np.random.randint(1,6)


3

In [42]:
arr.max()

3

In [43]:
arr.min()

1

In [44]:
arr


array([1, 2, 3])

In [45]:
arr.argmax()


2

In [47]:
arr.argmin()

0

In [48]:
arr.dtype

dtype('int64')

In [51]:
arr_2d =[[5,10,15],[20,25,30],[35,40,45]]


In [52]:
arr_2d

[[5, 10, 15], [20, 25, 30], [35, 40, 45]]

In [61]:
arr1=np.arange(1,11)

In [62]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr > 5

array([False, False, False])

In [64]:
arr >7

array([False, False, False])

In [65]:
arr.dtype

dtype('int64')

In [68]:
arr_2dd=np.arange(50).reshape(5,10)

In [69]:
arr_2dd

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [70]:
arr_2dd[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [75]:
arr_2dd[0:2,0:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [76]:
#numpyOperation


In [78]:
arr=np.arange(0,10)

In [79]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [82]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [87]:
arr = np.arange(9).reshape(3,3)

In [88]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
np.random.randint(0,9)

5

In [95]:
arr=np.random.rand(25)

In [96]:
arr

array([0.1729099 , 0.6761603 , 0.92062197, 0.121476  , 0.26690241,
       0.11344593, 0.20204733, 0.06688152, 0.82165972, 0.02032754,
       0.75704557, 0.17734914, 0.08782363, 0.98868118, 0.1441533 ,
       0.47360281, 0.26573612, 0.10440808, 0.69378451, 0.02671539,
       0.08128444, 0.02663547, 0.3734362 , 0.5224399 , 0.1790498 ])