In [4]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
from sklearn.linear_model import LinearRegression

In [3]:
model = LinearRegression()
print(model)


LinearRegression()


In [4]:
LinearRegression(copy_X=True,fit_intercept=True)

LinearRegression()

In [18]:
#spliting the data into traing data and test data

In [5]:
import numpy as np

In [12]:
from sklearn.model_selection import train_test_split

In [17]:
x,y=np.arange(10).reshape((5,2)),range(5)

<IPython.core.display.Javascript object>

In [18]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [19]:
list(y)


[0, 1, 2, 3, 4]

In [20]:
list(x)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [21]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

In [22]:
x_train

array([[6, 7],
       [0, 1],
       [4, 5]])

In [23]:
y_train

[3, 0, 2]

In [24]:
x_test

array([[8, 9],
       [2, 3]])

In [25]:
y_test

[4, 1]

In [27]:
#model.fit(x_train,y_train) to fit and train the model